//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscAnalyzerViewModel.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscAnalyzerViewModel.Resourses.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Bytes per Cluster ({1}).
        /// </summary>
        public static string ClusterSizeInfo {
            get {
                return ResourceManager.GetString("ClusterSizeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Space: {0} (of {1}).
        /// </summary>
        public static string DiscFreeSpaceInfo {
            get {
                return ResourceManager.GetString("DiscFreeSpaceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} Files.
        /// </summary>
        public static string FilesCountInfo {
            get {
                return ResourceManager.GetString("FilesCountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path is incorrect.
        /// </summary>
        public static string IncorrectFilePath {
            get {
                return ResourceManager.GetString("IncorrectFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of Parent ({0}).
        /// </summary>
        public static string PercentOfParentColumnName {
            get {
                return ResourceManager.GetString("PercentOfParentColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} Bytes.
        /// </summary>
        public static string SizeInBytes {
            get {
                return ResourceManager.GetString("SizeInBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N1} GB.
        /// </summary>
        public static string SizeInGb {
            get {
                return ResourceManager.GetString("SizeInGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N1} KB.
        /// </summary>
        public static string SizeInKb {
            get {
                return ResourceManager.GetString("SizeInKb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N1} MB.
        /// </summary>
        public static string SizeInMb {
            get {
                return ResourceManager.GetString("SizeInMb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N1} TB.
        /// </summary>
        public static string SizeInTb {
            get {
                return ResourceManager.GetString("SizeInTb", resourceCulture);
            }
        }
    }
}
